// Code generated by reset generator; DO NOT EDIT.

package model

func (s *TestReset) Reset() {
	if s == nil {
		return
	}
	s.IntVal = 0
	s.StrVal = ""
	s.BoolVal = false
	s.SliceVal = s.SliceVal[:0]
	clear(s.MapVal)
	if s.PtrVal != nil {
		if r, ok := any(s.PtrVal).(interface{ Reset() }); ok {
			r.Reset()
		} else {
			*s.PtrVal = ""
		}
	}
}
