package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Dir:  ".",
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		panic(err)
	}

	for _, pkg := range pkgs {
		processPackage(pkg)
	}
}

func processPackage(pkg *packages.Package) {
	var out bytes.Buffer

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				// FIX: ищем комментарий и в gen.Doc, и в ts.Doc
				if !hasResetComment(gen.Doc) && !hasResetComment(ts.Doc) {
					continue
				}

				generateReset(&out, ts.Name.Name, st)
			}
		}
	}

	if out.Len() == 0 {
		return
	}

	writeFile(pkg, out.Bytes())
}

func hasResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func writeFile(pkg *packages.Package, code []byte) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by reset generator; DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkg.Name + "\n\n")

	buf.Write(code)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	dir := filepath.Dir(pkg.GoFiles[0])
	file := filepath.Join(dir, "reset.gen.go")

	_ = os.WriteFile(file, formatted, 0644)
}

func generateReset(out *bytes.Buffer, structName string, st *ast.StructType) {
	fmt.Fprintf(out, "func (s *%s) Reset() {\n", structName)
	fmt.Fprintf(out, "\tif s == nil { return }\n")

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		name := field.Names[0].Name

		switch t := field.Type.(type) {

		case *ast.ArrayType: // slice
			fmt.Fprintf(out, "\ts.%s = s.%s[:0]\n", name, name)

		case *ast.MapType:
			fmt.Fprintf(out, "\tclear(s.%s)\n", name)

		case *ast.StarExpr: // pointer
			fmt.Fprintf(out, "\tif s.%s != nil {\n", name)

			// если есть Reset()
			fmt.Fprintf(out, "\t\tif r, ok := any(s.%s).(interface{ Reset() }); ok {\n", name)
			fmt.Fprintf(out, "\t\t\tr.Reset()\n")
			fmt.Fprintf(out, "\t\t} else {\n")

			// иначе сброс значения
			fmt.Fprintf(out, "\t\t\t*s.%s = %s\n", name, zeroValue(t.X))

			fmt.Fprintf(out, "\t\t}\n")
			fmt.Fprintf(out, "\t}\n")

		default:
			fmt.Fprintf(out, "\ts.%s = %s\n", name, zeroValue(t))
		}
	}

	fmt.Fprintf(out, "}\n\n")
}

func zeroValue(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int64", "float64":
			return "0"
		case "string":
			return `""`
		case "bool":
			return "false"
		}
	}
	return "nil"
}