syntax = "proto3";

package metrics;

option go_package = "github.com/ilyinon/go-musthave-metrics/internal/proto/metricspb";

// Metric defines a single metric.
message Metric {
  string id = 1;

  // MType defines the metric type.
  enum MType {
    GAUGE = 0;
    COUNTER = 1;
  }

  MType type = 2;
  int64 delta = 3;
  double value = 4;
}

// UpdateMetricsRequest contains metrics to update.
message UpdateMetricsRequest {
  repeated Metric metrics = 1;
}

// UpdateMetricsResponse confirms a successful update.
message UpdateMetricsResponse {}

// Metrics defines metrics operations.
service Metrics {
  // UpdateMetrics updates a single metric or a batch of metrics.
  rpc UpdateMetrics(UpdateMetricsRequest) returns (UpdateMetricsResponse);
}
